version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: gmah_postgres
    environment:
      POSTGRES_USER: gmah
      POSTGRES_PASSWORD: gmah_password_dev
      POSTGRES_DB: gmah_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gmah_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gmah"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: gmah_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - gmah_network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: gmah_minio
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_password_dev
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - gmah_network
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  gmah_network:
    driver: bridge